routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
/**/ 
/*FE*/ 
Route::get('/', function () {
    return view('fe.index');
});


/*BE*/ 
	Auth::routes();
	Route::get('/home', 'HomeController@index')->name('home');
	Route::resource('user', 'User\UserController');
	Route::post('user/update/{s}', 'User\UserController@update');
	Route::get('user/delete/{s}', 'User\UserController@destroy');	
	Route::resource('roles', 'User\RolesController');
	Route::post('roles/update/{s}', 'User\RolesController@update');
	Route::get('roles/delete/{s}', 'User\RolesController@destroy');
	Route::resource('product', 'Product\ProductController');
	Route::get('product/delete/{s}', 'Product\ProductController@destroy');
	Route::post('product/update/{s}', 'Product\ProductController@update');
	Route::resource('order', 'Order\OrderController');
	Route::post('order/addproduct', 'Order\OrderController@addproduct');
	Route::get('order/deleteproduct/{s}/{d}', 'Order\OrderController@deleteproduct');
	Route::post('order/update/{s}', 'Order\OrderController@update');
	Route::get('order/delete/{s}', 'Order\OrderController@destroy');
	Route::get('order/forward/{s}', 'Order\OrderController@forward');
	Route::get('order/invoice/{s}', 'Order\OrderController@invoice');
	Route::get('order/download/{s}', 'Order\OrderController@pdf');
	Route::get('order/scan/{s}', 'Order\OrderController@scan');
	Route::get('order/status/{id}/{status}', 'Order\OrderController@status');
	Route::resource('vendors', 'Vendor\VendorController');
	Route::get('vendors/delete/{s}', 'Vendor\VendorController@destroy');
	Route::post('vendors/update/{s}', 'Vendor\VendorController@update');
	Route::resource('uom', 'Uom\UomController');
	Route::post('uom/update/{s}', 'Uom\UomController@update');
	Route::get('uom/delete/{s}', 'Uom\UomController@destroy');

	

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
class Product extends Model
{
    use SoftDeletes;
     protected $table = 'products';
     protected $dates = ['deleted_at'];
     protected $fillable = [
        'code', 'name', 'desc','uom'
    ];

     public function hasUom(){

    	 return $this->belongsTo('App\Models\Uom','uom','id');
    }

}

app/Http/Controllers/Product/ProductController.php
<?php

namespace App\Http\Controllers\Product;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Product;

class ProductController extends Controller
{
     /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
       
        return view('product.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        return view('product.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        try {
                
            /*STORE DATA*/

            $this->validate($request, [
                'name' => 'required',
                'code' => 'required',
                'uom' => 'required',
                'desc' => 'max:225',
            ]);

            $store          = Product::create($request->all());
            \Session::flash('success', 'Success Add Product!'); 
    
            /*END STORE DATA*/ 
        
        }
        catch (\Exception $e) {
            
            \Session::flash('error', $e->getMessage()); 
        
        }
        
        return redirect()->route('product.index');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

        $data = Product::findOrFail($id);
        return view('product.edit',compact('data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        try {

             $this->validate($request, [
                'name' => 'required',
                'code' => 'required',
                'uom' => 'required',
                'desc' => 'max:225',
            ]);
            $update = Product::findOrFail($id)->update($request->all());
            \Session::flash('success', 'Success Update Product!'); 

        }
        catch (\Exception $e) {
            
            \Session::flash('error', $e->getMessage()); 
        
        }
        
        return redirect()->route('product.index');


    }   

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {

            $delete = Product::findOrFail($id)->delete();
            \Session::flash('success', 'Success Delete Product!'); 


        }
        catch (\Exception $e) {
            
            \Session::flash('error', $e->getMessage()); 
        
        }

        return redirect()->route('product.index');
    }
}

resources/views/product/create.blade.php
@extends('layouts.admin')
@section('content')
   <div class="page-breadcrumb">
                <div class="row">
                    <div class="col-12 d-flex no-block align-items-center">
                        <h4 class="page-title">Add Product</h4>
                        <div class="ml-auto text-right">
                            <nav aria-label="breadcrumb">
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item"><a href="{{route('product.index')}}">Product</a></li>
                                    <li class="breadcrumb-item active" aria-current="page">Add Product</li>
                                </ol>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>

	  <div class="card">

            <div class="card-body">
           			 <form class="form-horizontal" method="POST" action="{{ route('product.store') }}">
           			 	   {{ csrf_field() }}
                                <div class="card-body">
                                    <div class="form-group row">
                                        <label for="fname" class="col-sm-3 text-right control-label col-form-label">Product Name</label>
                                        <div class="col-sm-9">
                                            <input type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" id="fname" name="name" placeholder="Ex:BAJU" required="">
                                            @if ($errors->has('name'))
	                                          <div class="invalid-feedback">
	                                            {{ $errors->first('name') }}
	                                        </div>
	                                        @endif
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label for="lname" class="col-sm-3 text-right control-label col-form-label">Product Code</label>
                                        <div class="col-sm-9">
                                            <input type="text" name="code" class="form-control{{ $errors->has('code') ? ' is-invalid' : '' }}" id="lname" placeholder="Ex:BJ001" required="">
                                             @if ($errors->has('code'))
	                                            <div class="invalid-feedback">
	                                            {{ $errors->first('code') }}
	                                        </div>
	                                        @endif
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label for="email1" class="col-sm-3 text-right control-label col-form-label">Uom</label>
                                        <div class="col-sm-9">
                                               <select class="form-control{{ $errors->has('uom') ? ' is-invalid' : '' }}" name="uom" required>
                                           		@foreach(App\Models\Uom::all() as $index=>$row)
                                           		 <option value="{{$row->id}}">{{$row->name}}</option>
                                           		@endforeach
                                        		</select>
                                        	 @if ($errors->has('uom'))
	                                            <div class="invalid-feedback">
	                                            {{ $errors->first('uom') }}
	                                        </div>
	                                        @endif
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label for="cono1" class="col-sm-3 text-right control-label col-form-label">Description</label>
                                        <div class="col-sm-9">
                                            <textarea class="form-control{{ $errors->has('desc') ? ' is-invalid' : '' }}" name="desc"></textarea>
	                                            @if ($errors->has('desc'))
	                                            <div class="invalid-feedback">
	                                            {{ $errors->first('desc') }}
	                                        </div>
	                                        @endif

                                        </div>
                                    </div>
                                </div>
                                <div class="border-top">
                                    <div class="card-body">
                                        <button type="submit" class="btn btn-primary">Submit</button>
                                    </div>
                                </div>
                            </form>

            </div>
        </div>
@endsection

resources/views/product/edit.blade.php
@extends('layouts.admin')
@section('content')
   <div class="page-breadcrumb">
                <div class="row">
                    <div class="col-12 d-flex no-block align-items-center">
                        <h4 class="page-title">Edit Product</h4>
                        <div class="ml-auto text-right">
                            <nav aria-label="breadcrumb">
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item"><a href="{{route('product.index')}}">Product</a></li>
                                    <li class="breadcrumb-item active" aria-current="page">Edit Product</li>
                                </ol>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>

	  <div class="card">
            <div class="card-body">
           			 <form class="form-horizontal" method="POST" action="{{ url('product/update') }}/{{$data->id}}">
           			 	   {{ csrf_field() }}
                                <div class="card-body">
                                    <div class="form-group row">
                                        <label for="fname" class="col-sm-3 text-right control-label col-form-label">Product Name</label>
                                        <div class="col-sm-9">
                                            <input type="text" class="form-control{{ $errors->has('emp_code') ? ' is-invalid' : '' }}" id="fname" name="name" value="{{$data->name}}" placeholder="Ex:BAJU"  required="">
                                            @if ($errors->has('name'))
	                                          <div class="invalid-feedback">
	                                            {{ $errors->first('name') }}
	                                        </div>
	                                        @endif
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label for="lname" class="col-sm-3 text-right control-label col-form-label">Product Code</label>
                                        <div class="col-sm-9">
                                            <input type="text" name="code" value="{{$data->code}}" class="form-control{{ $errors->has('code') ? ' is-invalid' : '' }}" id="lname" placeholder="Ex:BJ001" required="">
                                             @if ($errors->has('code'))
	                                            <div class="invalid-feedback">
	                                            {{ $errors->first('code') }}
	                                        </div>
	                                        @endif
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label for="email1" class="col-sm-3 text-right control-label col-form-label">Uom</label>
                                        <div class="col-sm-9">
                                               <select class="form-control{{ $errors->has('uom') ? ' is-invalid' : '' }}" name="uom" required>
                                           		@foreach(App\Models\Uom::all() as $index=>$row)

                                           		 <option value="{{$row->id}}" @if($data->uom == $row->id) selected @endif>{{$row->name}}</option>
                                           		@endforeach
                                        		</select>
                                        	 @if ($errors->has('uom'))
	                                            <div class="invalid-feedback">
	                                            {{ $errors->first('uom') }}
	                                        </div>
	                                        @endif


                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label for="cono1" class="col-sm-3 text-right control-label col-form-label">Description</label>
                                        <div class="col-sm-9">
                                            <textarea class="form-control{{ $errors->has('desc') ? ' is-invalid' : '' }}" name="desc">{{$data->desc}}</textarea>
	                                            @if ($errors->has('desc'))
	                                            <div class="invalid-feedback">
	                                            {{ $errors->first('desc') }}
	                                        </div>
	                                        @endif

                                        </div>
                                    </div>
                                </div>
                                <div class="border-top">
                                    <div class="card-body">
                                        <button type="submit" class="btn btn-primary">Submit</button>
                                    </div>
                                </div>
                            </form>

            </div>
        </div>
@endsection

resources/views/product/index.blade.php
@extends('layouts.admin')
@section('css')
<link href="{{ url('public/admin/assets/libs/datatables.net-bs4/css/dataTables.bootstrap4.css')}}" rel="stylesheet">
@endsection
@section('content')
       <div class="page-breadcrumb">
                <div class="row">
                    <div class="col-12 d-flex no-block align-items-center">
                        <h4 class="page-title">Product</h4>
                        <div class="ml-auto text-right">
                            <nav aria-label="breadcrumb">
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                                    <li class="breadcrumb-item active" aria-current="page">Product</li>
                                </ol>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>

	  <div class="card">

                            <div class="card-body">
                                 @if(in_array('product_create',json_decode(\Auth::user()->hasRoles->access_permission)->data))
                            		<a href="{{route('product.create')}}"><button class="btn btn-primary btn-md"><i class="mdi mdi-cart-plus"></i> Add Product</button></a>
                                @endif
		                    	<hr>
                                <div class="table-responsive">
                                    <table id="zero_config" class="table table-striped table-bordered">
                                        <thead>
                                            <tr>
                                                <th>Name</th>
                                                <th>Code</th>
                                                <th>Desc</th>
                                                <th>Uom</th>
                                                <th>Created At</th>
                                                <th>Action</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach(App\Models\Product::all() as $index=>$row)
                                   	        <tr>
                                                <td>{{$row->name}}</td>
                                                <td>{{$row->code}}</td>
                                                <td>{{$row->desc}}</td>
                                                <td>{{$row->hasUom->name}}</td>
                                                <td>{{$row->created_at}}</td>
                                                <td>
                                                    @if(in_array('product_delete',json_decode(\Auth::user()->hasRoles->access_permission)->data))
                                                    <a href="{{ url('product/delete/')}}/{{$row->id}}" ><button class="btn btn-danger btn-md"><i class="fas fa-trash"></i></button></a> 
                                                    @endif
                                                    @if(in_array('product_edit',json_decode(\Auth::user()->hasRoles->access_permission)->data))
                                                    <a href="{{route('product.edit',$row->id)}}"><button class="btn btn-primary btn-md"><i class="fas fa-edit"></i></button></a></td>
                                                    @endif
                                            </tr>
                                            @endforeach
                                        </tbody>
                                   
                                    </table>
                                </div>

                            </div>
                        </div>

@endsection
@section('js')
<script src="{{ url('public/admin/assets/extra-libs/DataTables/datatables.min.js')}}"></script>
<script type="text/javascript">
	$('#zero_config').DataTable();
</script>
@endsection