routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
/**/ 
/*FE*/ 
Route::get('/', function () {
    return view('fe.index');
});


/*BE*/ 
	Auth::routes();
	Route::get('/home', 'HomeController@index')->name('home');
	Route::resource('user', 'User\UserController');
	Route::post('user/update/{s}', 'User\UserController@update');
	Route::get('user/delete/{s}', 'User\UserController@destroy');	
	Route::resource('roles', 'User\RolesController');
	Route::post('roles/update/{s}', 'User\RolesController@update');
	Route::get('roles/delete/{s}', 'User\RolesController@destroy');
	Route::resource('product', 'Product\ProductController');
	Route::get('product/delete/{s}', 'Product\ProductController@destroy');
	Route::post('product/update/{s}', 'Product\ProductController@update');
	Route::resource('order', 'Order\OrderController');
	Route::post('order/addproduct', 'Order\OrderController@addproduct');
	Route::get('order/deleteproduct/{s}/{d}', 'Order\OrderController@deleteproduct');
	Route::post('order/update/{s}', 'Order\OrderController@update');
	Route::get('order/delete/{s}', 'Order\OrderController@destroy');
	Route::get('order/forward/{s}', 'Order\OrderController@forward');
	Route::get('order/invoice/{s}', 'Order\OrderController@invoice');
	Route::get('order/download/{s}', 'Order\OrderController@pdf');
	Route::get('order/scan/{s}', 'Order\OrderController@scan');
	Route::get('order/status/{id}/{status}', 'Order\OrderController@status');
	Route::resource('vendors', 'Vendor\VendorController');
	Route::get('vendors/delete/{s}', 'Vendor\VendorController@destroy');
	Route::post('vendors/update/{s}', 'Vendor\VendorController@update');
	Route::resource('uom', 'Uom\UomController');
	Route::post('uom/update/{s}', 'Uom\UomController@update');
	Route::get('uom/delete/{s}', 'Uom\UomController@destroy');

	

app/Models/Uom.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
class Uom extends Model
{
	 use SoftDeletes;
     protected $table = 'uom';
     
     protected $fillable = [
         'name'
    ];}

app/Http/Controllers/Uom/UomController.php
<?php

namespace App\Http\Controllers\Uom;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Uom;

class UomController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('uom.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
         return view('uom.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try{
          $this->validate($request, [
            'name' => 'required',
        ]);
        $uom = Uom::create($request->all());
        \Session::flash('success', 'Success Add Uom!'); 

        }
        catch (\Exception $e) {
            
            \Session::flash('error', $e->getMessage()); 
        
        }
        return redirect()->route('uom.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

        $data = Uom::findOrFail($id);
        return view('uom.edit',compact('data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        try{
          $this->validate($request, [
            'name' => 'required',
        ]);
        $uom = Uom::findOrFail($id)->update($request->all());
         \Session::flash('success', 'Success Update Uom!'); 

        }
        catch (\Exception $e) {
            
            \Session::flash('error', $e->getMessage()); 
        
        }
        return redirect()->route('uom.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try{
         $uom = Uom::findOrFail($id)->delete();
        \Session::flash('success', 'Success Delete Uom!'); 

        }
        catch (\Exception $e) {
            
            \Session::flash('error', $e->getMessage()); 
        
        }
        return redirect()->route('uom.index');
    }
}

resources/views/uom/create.blade.php
@extends('layouts.admin')

@section('content')
<div class="page-breadcrumb">
                <div class="row">
                    <div class="col-12 d-flex no-block align-items-center">
                        <h4 class="page-title">Create Uom</h4>
                        <div class="ml-auto text-right">
                            <nav aria-label="breadcrumb">
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item"><a href="{{route('roles.index')}}">Uom</a></li>
                                    <li class="breadcrumb-item active" aria-current="page">Create Uom</li>
                                </ol>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>

      <div class="card">

            <div class="card-body">
                       <form class="form-horizontal" method="POST" action="{{ route('uom.store') }}">
                             {{ csrf_field() }}
                                <div class="card-body">
                                    <div class="form-group row">
                                        <label for="fname" class="col-sm-3 text-right control-label col-form-label">Name</label>
                                        <div class="col-sm-9">
                                            <input type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}"  name="name" value="{{ old('name') }}" placeholder="Ex:Kg" >
                                            @if ($errors->has('name'))
                                              <div class="invalid-feedback">
                                                {{ $errors->first('name') }}
                                            </div>
                                            @endif
                                        </div>
                                    </div>
                                </div>
                                <div class="border-top">
                                    <div class="card-body">
                                        <button type="submit" class="btn btn-primary">Submit</button>
                                    </div>
                                </div>
                            </form>

            </div>
        </div>

@endsection

resources/views/uom/edit.blade.php
@extends('layouts.admin')

@section('content')
<div class="page-breadcrumb">
                <div class="row">
                    <div class="col-12 d-flex no-block align-items-center">
                        <h4 class="page-title">Edit Uom</h4>
                        <div class="ml-auto text-right">
                            <nav aria-label="breadcrumb">
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item"><a href="{{route('uom.index')}}">Uom</a></li>
                                    <li class="breadcrumb-item active" aria-current="page">Edit Uom</li>
                                </ol>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>

      <div class="card">

            <div class="card-body">
                       <form class="form-horizontal" method="POST" action="{{ url('uom/update') }}/{{$data->id}}">
                             {{ csrf_field() }}
                                <div class="card-body">
                                    <div class="form-group row">
                                        <label for="fname" class="col-sm-3 text-right control-label col-form-label">Name</label>
                                        <div class="col-sm-9">
                                            <input type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}"  name="name" value="{{ $data->name }}" placeholder="Ex:Kg" >
                                            @if ($errors->has('name'))
                                              <div class="invalid-feedback">
                                                {{ $errors->first('name') }}
                                            </div>
                                            @endif
                                        </div>
                                    </div>
                                </div>
                                <div class="border-top">
                                    <div class="card-body">
                                        <button type="submit" class="btn btn-primary">Submit</button>
                                    </div>
                                </div>
                            </form>

            </div>
        </div>

@endsection

resources/views/uom/index.blade.php
@extends('layouts.admin')
@section('css')
<link href="{{ url('public/admin/assets/libs/datatables.net-bs4/css/dataTables.bootstrap4.css')}}" rel="stylesheet">
@endsection
@section('content')
       <div class="page-breadcrumb">
                <div class="row">
                    <div class="col-12 d-flex no-block align-items-center">
                        <h4 class="page-title">Uom</h4>
                        <div class="ml-auto text-right">
                            <nav aria-label="breadcrumb">
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item"><a href="{{url('/home')}}">Home</a></li>
                                    <li class="breadcrumb-item active" aria-current="page">Uom</li>
                                </ol>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
	     <div class="card">
            <div class="card-body">
                 @if(in_array('uom_add',json_decode(\Auth::user()->hasRoles->access_permission)->data))
            		<a href="{{route('uom.create')}}"><button class="btn btn-primary btn-md"><i class="mdi mdi-weight"></i> Add Uom</button></a>
                    @endif
            	<hr>
                <div class="table-responsive">
                    <table id="zero_config" class="table table-striped table-bordered">
                        <thead>
                            <tr>
                                <th>No</th>
                                <th>Name</th>
                                <th>Created At</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach(App\Models\Uom::all() as $index=>$row)
                   	        <tr>
                                <td>{{$index+1}}</td>
                                <td>{{$row->name}}</td>
                                <td>{{$row->created_at}}</td>
                                <td>
                                    @if(in_array('uom_delete',json_decode(\Auth::user()->hasRoles->access_permission)->data))
                                    <a href="{{ url('uom/delete/')}}/{{$row->id}}" ><button class="btn btn-danger btn-md"><i class="fas fa-trash"></i></button></a> 
                                    @endif
                                    @if(in_array('uom_edit',json_decode(\Auth::user()->hasRoles->access_permission)->data))
                                    <a href="{{route('uom.edit',$row->id)}}"><button class="btn btn-primary btn-md"><i class="fas fa-edit"></i></button></a></td>
                                    @endif
                            </tr>
                            @endforeach
                        </tbody>
                   
                    </table>
                </div>

            </div>
        </div>

@endsection
@section('js')
<script src="{{ url('public/admin/assets/extra-libs/DataTables/datatables.min.js')}}"></script>
<script type="text/javascript">
	$('#zero_config').DataTable();
</script>
@endsection