routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
/**/ 
/*FE*/ 
Route::get('/', function () {
    return view('fe.index');
});


/*BE*/ 
	Auth::routes();
	Route::get('/home', 'HomeController@index')->name('home');
	Route::resource('user', 'User\UserController');
	Route::post('user/update/{s}', 'User\UserController@update');
	Route::get('user/delete/{s}', 'User\UserController@destroy');	
	Route::resource('roles', 'User\RolesController');
	Route::post('roles/update/{s}', 'User\RolesController@update');
	Route::get('roles/delete/{s}', 'User\RolesController@destroy');
	Route::resource('product', 'Product\ProductController');
	Route::get('product/delete/{s}', 'Product\ProductController@destroy');
	Route::post('product/update/{s}', 'Product\ProductController@update');
	Route::resource('order', 'Order\OrderController');
	Route::post('order/addproduct', 'Order\OrderController@addproduct');
	Route::get('order/deleteproduct/{s}/{d}', 'Order\OrderController@deleteproduct');
	Route::post('order/update/{s}', 'Order\OrderController@update');
	Route::get('order/delete/{s}', 'Order\OrderController@destroy');
	Route::get('order/forward/{s}', 'Order\OrderController@forward');
	Route::get('order/invoice/{s}', 'Order\OrderController@invoice');
	Route::get('order/download/{s}', 'Order\OrderController@pdf');
	Route::get('order/scan/{s}', 'Order\OrderController@scan');
	Route::get('order/status/{id}/{status}', 'Order\OrderController@status');
	Route::resource('vendors', 'Vendor\VendorController');
	Route::get('vendors/delete/{s}', 'Vendor\VendorController@destroy');
	Route::post('vendors/update/{s}', 'Vendor\VendorController@update');
	Route::resource('uom', 'Uom\UomController');
	Route::post('uom/update/{s}', 'Uom\UomController@update');
	Route::get('uom/delete/{s}', 'Uom\UomController@destroy');

	

app/Models/Order.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
     protected $table = 'order';
     
     protected $fillable = [
        'no_order','status','notes','vendor_id','shipment_date','created_by'
    ];

    public function hasVendor(){

         return $this->belongsTo('App\Models\Vendor','vendor_id','id')->withTrashed();
    }
    public function hasStatus(){

         return $this->belongsTo('App\Models\StatusOrder','status','id');
    }
    public function hasOrderDetail(){

    	 return $this->hasMany('App\Models\OrderDetail','order_id','id');
    }
}

app/Http/Controllers/Order/OrderController.php
<?php

namespace App\Http\Controllers\Order;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Order;
use App\Models\OrderDetail;
use Illuminate\Support\Facades\Mail;
use App\Mail\OrderShipped;

class OrderController extends Controller
{
     /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
        
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('order.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('order.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try{
        /*store order*/ 
          $this->validate($request, [
            'no_order' => 'required',
            'shipment_date' => 'required',
            'vendor_id' => 'required',
        ]);
        $data                   = $request->all();
        $data['shipment_date']  = \Carbon\Carbon::parse($request->shipment_date)->toDateTimeString();
        $data['status']         = 1;/*pending*/
        $data['created_by']     = \Auth::user()->id;
        $store                  = Order::create($data);
        /*end store order*/ 
         \Session::flash('success', 'Success Add Order!'); 
    
            /*END STORE DATA*/ 
        
        }
        catch (\Exception $e) {
            
            \Session::flash('error', $e->getMessage()); 
        
        }
        return redirect()->route('order.index');

    }


    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data = Order::findOrFail($id);
        return view('order.detail',compact('data'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function forward($id)
    {
        try{
        $order = Order::findOrFail($id);
            Mail::to($order->hasVendor->email)->send(new OrderShipped($order));
            $order->update(['status' => 3]);
         \Session::flash('success', 'Success Send Order!'); 
    
            /*END STORE DATA*/ 
        
        }
        catch (\Exception $e) {
            
            \Session::flash('error', $e->getMessage()); 
        
        }
        return redirect()->route('order.show',$id);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        try{
          $this->validate($request, [
            'shipment_date' => 'required',
            'vendor_id' => 'required',
        ]);

        $data                   = $request->all();
        $data['shipment_date']  = \Carbon\Carbon::parse($request->shipment_date)->toDateTimeString();
        $update = Order::findOrFail($id)->update($data);
         \Session::flash('success', 'Success Update Order!'); 
    
            /*END STORE DATA*/ 
        
        }
        catch (\Exception $e) {
            
            \Session::flash('error', $e->getMessage()); 
        
        }
        return redirect()->route('order.show',$id);
    } 

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        /* cancel order == 2*/ 
        $cancel      = Order::findOrFail($id)->update(['status' => 2]);
        /* end cancel order */ 
        return redirect()->route('order.show',$id);
    } 

    public function invoice($id)
    {
        $data = Order::findOrFail($id);
       return view('templates.print',compact('data'));
    }
    public function pdf($id)
    {
        $data = Order::findOrFail($id);
        $pdf = \PDF::loadView('templates/invoice',['data' => $data]);
        $pdf->setOptions(['dpi' => 150, 'defaultFont' => 'sans-serif']);
        $pdf->setPaper('A4', 'portrait');
        return $pdf->download($data->no_order.'.pdf');
    }

    public function addproduct(Request $request)
    {
        try{
        
        $data                   = $request->all();
        $data['qty_total']      = str_replace(",", "", $request->qty_total);
        $data['status']         = 3;
        $store                  = OrderDetail::create($data);
        /* Update Order Detail*/

        $update                 = OrderDetail::findOrFail($store->id)->update(['code' => uniqid()]);

        /* End Update Order Detail */ 
         \Session::flash('success', 'Success Add Product Order!'); 
        
        }
        catch (\Exception $e) {
            
            \Session::flash('error', $e->getMessage()); 
        
        }
        return redirect()->route('order.show',$request->order_id);
    }
    public function deleteproduct($id,$idorder)
    {
        try{
        $cancel      = OrderDetail::findOrFail($id)->delete();
     
        \Session::flash('success', 'Success Delete Product Order!'); 
        
        }
        catch (\Exception $e) {
            
            \Session::flash('error', $e->getMessage()); 
        
        }
        return redirect()->route('order.show',$idorder);
    } 

    public function scan($orderno)
    { 
     
        $order      = Order::where('no_order','LIKE',$orderno)->first();
        return $order; 
    } 
    
    public function status($id,$status)
    { 
        try{
        $order      = Order::findOrFail($id)->update(['status' => $status]);
         \Session::flash('success', 'Success Change Status Order!'); 
        
        }
        catch (\Exception $e) {
            
            \Session::flash('error', $e->getMessage()); 
        
        }
        return redirect()->route('order.show',$id); 
    } 
}

resources/views/order/create.blade.php
@extends('layouts.admin')
@section('css')
<link rel="stylesheet" type="text/css" href="{{ url('public/admin/assets/libs/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css')}}">
@endsection
@section('content')
   <div class="page-breadcrumb">
                <div class="row">
                    <div class="col-12 d-flex no-block align-items-center">
                        <h4 class="page-title">Add Order</h4>
                        <div class="ml-auto text-right">
                            <nav aria-label="breadcrumb">
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item"><a href="{{route('order.index')}}">Order</a></li>
                                    <li class="breadcrumb-item active" aria-current="page">Add Order</li>
                                </ol>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>

	  <div class="card">

            <div class="card-body">
           			 <form class="form-horizontal" method="POST" action="{{ route('order.store') }}">
           			 	   {{ csrf_field() }}
                                <div class="card-body">
                                    <div class="form-group row">
                                        <label for="lname" class="col-sm-3 text-right control-label col-form-label">No Order</label>
                                        <div class="col-sm-9">
                                            <input type="text" name="no_order" class="form-control{{ $errors->has('no_order') ? ' is-invalid' : '' }}" id="lname" placeholder="Ex:XXX01">
                                             @if ($errors->has('no_order'))
                                                <div class="invalid-feedback">
                                                {{ $errors->first('no_order') }}
                                            </div>
                                            @endif
                                        </div>
                                    </div>
                                   
                                     <div class="form-group row">
                                        <label for="lname" class="col-sm-3 text-right control-label col-form-label">Supplier</label>
                                        <div class="col-sm-9">
                                             <select class="form-control{{ $errors->has('vendor_id') ? ' is-invalid' : '' }}" name="vendor_id" required>
                                                @foreach(App\Models\Vendor::all() as $index=>$row)
                                                 <option value="{{$row->id}}">{{$row->name}}</option>
                                                @endforeach
                                                </select>
                                             @if ($errors->has('vendor_id'))
                                                <div class="invalid-feedback">
                                                {{ $errors->first('vendor_id') }}
                                            </div>
                                            @endif
                                        </div>
                                    </div> 
                                    <div class="form-group row">
                                        <label for="lname" class="col-sm-3 text-right control-label col-form-label">Shipment Date</label>
                                        <div class="col-sm-9">
                                            <input type="text" name="shipment_date" class="form-control{{ $errors->has('shipment_date') ? ' is-invalid' : '' }} mydatepicker" placeholder="mm/dd/yyyy" id="lname" >
                                             @if ($errors->has('shipment_date'))
                                                <div class="invalid-feedback">
                                                {{ $errors->first('shipment_date') }}
                                            </div>
                                            @endif
                                        </div>
                                    </div>
                                    <!-- <div class="form-group row">
                                        <label for="cono1" class="col-sm-3 text-right control-label col-form-label">Notes</label>
                                        <div class="col-sm-9">
                                            <textarea class="form-control{{ $errors->has('notes') ? ' is-invalid' : '' }}" name="notes"></textarea>
                                                @if ($errors->has('notes'))
                                                <div class="invalid-feedback">
                                                {{ $errors->first('notes') }}
                                            </div>
                                            @endif

                                        </div>
                                    </div> 
                             -->

                                </div>
                                <div class="border-top">
                                    <div class="card-body">
                                        <button type="submit" class="btn btn-primary">Submit</button>
                                    </div>
                                </div>
                            </form>

            </div>
        </div>
@endsection
@section('js')
<script src="{{ url('public/admin/assets/libs/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js')}}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/accounting.js/0.4.1/accounting.min.js"></script>
<script type="text/javascript">
    jQuery('.mydatepicker').datepicker();
    /* count total */ 
    $('input[name=qty_satuan], input[name=qty_global]').keyup(function() {
        var qty_satuan = $('input[name=qty_satuan]').val()-0;
        var qty_global = $('input[name=qty_global]').val()-0;
        if (qty_satuan >= 0 && qty_global >= 0)
            var total = accounting.formatNumber(qty_satuan*qty_global)
            $('input[name=qty_total]').val(total)
    });
    /* end count total */ 
</script>
@endsection

resources/views/order/index.blade.php
@extends('layouts.admin')
@section('css')
<link href="{{ url('public/admin/assets/libs/datatables.net-bs4/css/dataTables.bootstrap4.css')}}" rel="stylesheet">
@endsection
@section('content')
       <div class="page-breadcrumb">
                <div class="row">
                    <div class="col-12 d-flex no-block align-items-center">
                        <h4 class="page-title">Order</h4>
                        <div class="ml-auto text-right">
                            <nav aria-label="breadcrumb">
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                                    <li class="breadcrumb-item active" aria-current="page">Order</li>
                                </ol>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>

	  <div class="card">
                    <div class="card-body">
                           @if(in_array('order_create',json_decode(\Auth::user()->hasRoles->access_permission)->data))
                            		<a href="{{route('order.create')}}"><button class="btn btn-primary btn-md"><i class="mdi mdi-cart-plus"></i> Add Order</button></a>
                          @endif
                           @if(in_array('order_scan',json_decode(\Auth::user()->hasRoles->access_permission)->data))
                                    <button class="btn btn-success btn-md" id="scanOrder"><i class="mdi mdi-scanner"></i> Scan Order</button>
                             @endif
		                    	<hr>
                                <div class="table-responsive">
                                    <table id="zero_config" class="table table-striped table-bordered">
                                        <thead>
                                            <tr>
                                                <th>Order No</th>
                                                <th>Vendor</th>
                                                <th>Shipment Date</th>
                                                <th>Created by</th>
                                                <th>Created at</th>
                                                <th>Status</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach(App\Models\Order::orderBy('created_at','desc')->get() as $index=>$row)
                                   	        <tr>
                                                <td>
                                                   @if(in_array('order_detail',json_decode(\Auth::user()->hasRoles->access_permission)->data))
                                                <a href="{{route('order.show',$row->id)}}">{{$row->no_order}}</a>
                                                  @else
                                                  {{$row->no_order}}
                                                  @endif
                                                </td>
                                               <td>{{$row->hasVendor->name or null}}</td>
                                                <td>{{\Carbon\Carbon::parse($row->shipment_date)->toDateString()}}</td>
                                                <td>{{\App\User::findOrFail($row->created_by)->name}}</td>
                                                <td>{{\Carbon\Carbon::parse($row->created_at)->toDateString()}}</td>
                                                <td>{{$row->hasStatus->name or null}}</td>
                                            </tr>
                                            @endforeach
                                        </tbody>
                                   
                                    </table>
                                </div>

                            </div>
                        </div>

                        <!-- Modal Scan  -->
                         <div class="modal fade" id="modalScanOrder" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                          <div class="modal-dialog modal-dialog-centered" role="document">
                            <div class="modal-content">
                              <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalLongTitle"><b>Scan Order</b></h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                  <span aria-hidden="true">&times;</span>
                                </button>
                              </div>
                              <div class="modal-body">
                                        <div class="form-group row">
                                           <div class="col-sm-12">
                                                   <input type="text"  class="form-control"   id="orderScan" onkeyup="lookup(this);" placeholder="Ex:74410">
                                            </div>
                                        </div>
                                      </div>
                                <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                </div>
                            </div>
                          </div>
                        </div>

@endsection
@section('js')
<script src="{{ url('public/admin/assets/extra-libs/DataTables/datatables.min.js')}}"></script>
<script type="text/javascript">
	$('#zero_config').DataTable({
        "order": []
});
     $('#scanOrder').click(function(){

        $('#modalScanOrder').modal('show');
    }); 

     function lookup(val){

         $.get( "{{ url('order/scan') }}/"+val.value, function( data ) {
                
                window.open("{{ url('order') }}/"+data.id);
                $('#modalScanOrder').modal('hide');
                $('#orderScan').val('');

         });
        
     }


</script>
@endsection