routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
/**/ 
/*FE*/ 
Route::get('/', function () {
    return view('fe.index');
});


/*BE*/ 
	Auth::routes();
	Route::get('/home', 'HomeController@index')->name('home');
	Route::resource('user', 'User\UserController');
	Route::post('user/update/{s}', 'User\UserController@update');
	Route::get('user/delete/{s}', 'User\UserController@destroy');	
	Route::resource('roles', 'User\RolesController');
	Route::post('roles/update/{s}', 'User\RolesController@update');
	Route::get('roles/delete/{s}', 'User\RolesController@destroy');
	Route::resource('product', 'Product\ProductController');
	Route::get('product/delete/{s}', 'Product\ProductController@destroy');
	Route::post('product/update/{s}', 'Product\ProductController@update');
	Route::resource('order', 'Order\OrderController');
	Route::post('order/addproduct', 'Order\OrderController@addproduct');
	Route::get('order/deleteproduct/{s}/{d}', 'Order\OrderController@deleteproduct');
	Route::post('order/update/{s}', 'Order\OrderController@update');
	Route::get('order/delete/{s}', 'Order\OrderController@destroy');
	Route::get('order/forward/{s}', 'Order\OrderController@forward');
	Route::get('order/invoice/{s}', 'Order\OrderController@invoice');
	Route::get('order/download/{s}', 'Order\OrderController@pdf');
	Route::get('order/scan/{s}', 'Order\OrderController@scan');
	Route::get('order/status/{id}/{status}', 'Order\OrderController@status');
	Route::resource('vendors', 'Vendor\VendorController');
	Route::get('vendors/delete/{s}', 'Vendor\VendorController@destroy');
	Route::post('vendors/update/{s}', 'Vendor\VendorController@update');
	Route::resource('uom', 'Uom\UomController');
	Route::post('uom/update/{s}', 'Uom\UomController@update');
	Route::get('uom/delete/{s}', 'Uom\UomController@destroy');

	

resources/views/include/alert.blade.php
@if ($message = Session::get('success'))
<div class="alert alert-success" role="alert">
	<button type="button" class="close" data-dismiss="alert">×</button>	
        <strong>{{ $message }}</strong>
</div>
@endif

@if ($message = Session::get('error'))
<div class="alert alert-danger" role="alert">
	<button type="button" class="close" data-dismiss="alert">×</button>	
        <strong>{{ $message }}</strong>
</div>
@endif

@if ($message = Session::get('warning'))
<div class="alert alert-warning" role="alert">
	<button type="button" class="close" data-dismiss="alert">×</button>	
	<strong>{{ $message }}</strong>
</div>
@endif

@if ($message = Session::get('info'))
<div class="alert alert-info" role="alert">
	<button type="button" class="close" data-dismiss="alert">×</button>	
	<strong>{{ $message }}</strong>
</div>
@endif

@if ($errors->any())
<div class="alert alert-danger" role="alert">
	<button type="button" class="close" data-dismiss="alert">×</button>	
	@foreach($errors->all() as $error)
        <li>{{ $error }}</li>
    @endforeach
</div>
@endif

resources/views/include/header.blade.php
   <header class="topbar" data-navbarbg="skin5">
            <nav class="navbar top-navbar navbar-expand-md navbar-dark">
                <div class="navbar-header" data-logobg="skin5">
                    <a class="nav-toggler waves-effect waves-light d-block d-md-none" href="javascript:void(0)"><i class="ti-menu ti-close"></i></a>
                    <a class="navbar-brand" href="{{url('/home')}}">
                        <b class="logo-icon p-l-10">
                            <img src="{{ url('/public/fe/images/logo_fav.ico')}}" alt="homepage" class="light-logo" />
                        </b>
                        <span class="logo-text">
                               DEATEX'S
                             </span>
                        </a>
                    <a class="topbartoggler d-block d-md-none waves-effect waves-light" href="javascript:void(0)" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><i class="ti-more"></i></a>
                </div>
                <div class="navbar-collapse collapse" id="navbarSupportedContent" data-navbarbg="skin5">
                    <ul class="navbar-nav float-left mr-auto">
                        <li class="nav-item d-none d-md-block"><a class="nav-link sidebartoggler waves-effect waves-light" href="javascript:void(0)" data-sidebartype="mini-sidebar"><i class="mdi mdi-menu font-24"></i></a></li>
                    </ul>
                    <ul class="navbar-nav float-right">
                  
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-muted waves-effect waves-dark pro-pic" href="" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><img src="{{ url('public/admin/assets/images/users/1.jpg')}}" alt="user" class="rounded-circle" width="31"></a>
                            <div class="dropdown-menu dropdown-menu-right user-dd animated">
                               <a class="dropdown-item" href="{{route('user.edit',Auth::user()->id)}}"><i class="ti-settings m-r-5 m-l-5"></i> Account Setting</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();"><i class="fa fa-power-off m-r-5 m-l-5"></i> Logout</a>
                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                            </div>
                        </li>
                       </ul>
                </div>
            </nav>
        </header>

    

resources/views/include/sidebar.blade.php
<aside class="left-sidebar" data-sidebarbg="skin5">
            <!-- Sidebar scroll-->
            <div class="scroll-sidebar">
                <!-- Sidebar navigation-->
                <nav class="sidebar-nav">
                    <ul id="sidebarnav" class="p-t-30">
                        <li class="sidebar-item"> <a class="sidebar-link waves-effect waves-dark sidebar-link" href="{{url('/home')}}" aria-expanded="false"><i class="mdi mdi-view-dashboard"></i><span class="hide-menu">Dashboard</span></a></li>
                         @if(in_array('order_view',json_decode(\Auth::user()->hasRoles->access_permission)->data))
                        <li class="sidebar-item"> <a class="sidebar-link waves-effect waves-dark sidebar-link" href="{{ route('order.index') }}" aria-expanded="false"><i class="mdi mdi-microsoft"></i><span class="hide-menu">Order</span></a></li>
                        @endif
                         @if(in_array('product_view',json_decode(\Auth::user()->hasRoles->access_permission)->data))
                        <li class="sidebar-item"> <a class="sidebar-link waves-effect waves-dark sidebar-link" href="{{ route('product.index') }}" aria-expanded="false"><i class="mdi mdi-package-variant-closed"></i><span class="hide-menu">Product</span></a></li>
                        @endif
                         @if(in_array('vendor_view',json_decode(\Auth::user()->hasRoles->access_permission)->data))
                        <li class="sidebar-item"> <a class="sidebar-link waves-effect waves-dark sidebar-link" href="{{ route('vendors.index') }}" aria-expanded="false"><i class="mdi mdi-bank"></i><span class="hide-menu">Supplier</span></a></li>
                        @endif
                         <li class="sidebar-item"> <a class="sidebar-link has-arrow waves-effect waves-dark" href="javascript:void(0)" aria-expanded="false"><i class="mdi mdi-settings"></i><span class="hide-menu">Settings </span></a>
                            <ul aria-expanded="false" class="collapse  first-level">
                                 @if(in_array('employee_view',json_decode(\Auth::user()->hasRoles->access_permission)->data))
                                 <li class="sidebar-item"> <a class="sidebar-link waves-effect waves-dark sidebar-link" href="{{ route('user.index') }}" aria-expanded="false"><i class="mdi mdi-account"></i><span class="hide-menu">Users</span></a></li>
                                 @endif
                                  @if(in_array('uom_view',json_decode(\Auth::user()->hasRoles->access_permission)->data))
                                <li class="sidebar-item"><a href="{{ route('uom.index') }}" class="sidebar-link"><i class="mdi mdi-weight"></i><span class="hide-menu"> Uom</span></a></li>
                                @endif

                            </ul>
                        </li>
                       
                        
                    </ul>
                </nav>
                <!-- End Sidebar navigation -->
            </div>
            <!-- End Sidebar scroll-->
        </aside>